Added Config Files Testing and Token Generation Check
samyak-jain/AgoraBackend pull request #10
Opened 2021-01-19 16:53 UTC by raysandeep

2021-01-19 16:54 UTC, raysandeep commented
@samyak-jain Please go through it.

2021-01-26 14:45 UTC, samyak-jain requested changes

2021-01-26 14:45 UTC, samyak-jain commented on utils/tokens_test.go
> +	channelName := "7d72365eb983485397e3e3f9d460bdda"
These credentials are not real, right? Maybe you can delete the project in your console?

2021-01-26 14:45 UTC, samyak-jain commented on utils/tokens_test.go
> +	token.FromString(result)
You need to assert that the token returned from result is the one that we expect. Same applies for the RTM Token as well.

2021-01-26 14:45 UTC, samyak-jain commented on utils/tokens_test.go
> +	uidZero := uint32(0)
It might be useful to use the UID generator already written with a mocked seed? Or use a more non trivial example

2021-02-25 15:33 UTC, raysandeep commented on utils/tokens_test.go
> +	channelName := "7d72365eb983485397e3e3f9d460bdda"
Nah. Not real.

2021-02-25 15:42 UTC, raysandeep commented on utils/tokens_test.go
> +	token.FromString(result)
I don't think we can do this. Coz we have expiry which will be dependant on time.

2021-02-25 18:11 UTC, samyak-jain commented on utils/tokens_test.go
> +	token.FromString(result)
The token generated is not being verified by Agora's servers anyway. After all, if we wanted that, we would need to use real credentials which we are not doing. We are doing this only to verify the correctness of the algorithm we are using. To check If all the parts are working properly or if there are any unforeseen panics in the code.

2021-03-04 13:08 UTC, samyak-jain commented on utils/tokens_test.go
> +	token.FromString(result)
@raysandeep Let me know once you have a chance to take a look into this

2021-03-04 13:09 UTC, samyak-jain commented on utils/tokens_test.go
> +	uidZero := uint32(0)
@raysandeep Does this make sense to you? Feel free to let me know if you have any questions.

2021-03-05 13:03 UTC, raysandeep commented on utils/tokens_test.go
> +	token.FromString(result)
I'll check and get back to you!

2021-03-05 13:04 UTC, raysandeep commented on utils/tokens_test.go
> +	uidZero := uint32(0)
I'm not really sure how to do this. Do you have any example in mind?

2021-03-10 13:30 UTC, samyak-jain commented on utils/tokens_test.go
> +	uidZero := uint32(0)
For now, hard code the UID to be something other than 0. It can be any random number. And as suggested previously, use multiple such hardcoded credentials to test this using Table Driven Development.

2021-03-23 15:16 UTC, merged