Added Tests
samyak-jain/AgoraBackend pull request #11
Opened 2021-01-30 10:58 UTC by raysandeep

Hey Samyak, 

I'm having an issue with the join room handler. 
The error is `[{"message":"must not be null","path":["getUser"]}]`
I've tried it on Graphql Playground getting the same error.
Do you mind helping me out with this?

2021-02-02 14:45 UTC, samyak-jain commented
The tests aren't running for me. The reason for this is that the suite is not properly integrated. Basically, the environment is not setup for TestWebOAuthHandler. Instead of manually calling setup, you should leverage testify to do that for you. 
Use this as reference: https://github.com/samyak-jain/AgoraBackend/blob/d2aeecbb476ede00060f6a4d5ddbfc9151511af2/test/server_test.go

In my code, ```go test``` will not run this function https://github.com/samyak-jain/AgoraBackend/blob/d2aeecbb476ede00060f6a4d5ddbfc9151511af2/test/server_test.go#L136 by default. It will only run https://github.com/samyak-jain/AgoraBackend/blob/d2aeecbb476ede00060f6a4d5ddbfc9151511af2/test/server_test.go#L257

That particular test is what will bootstrap the testing of all the other functions. This is so that testify can manage them (i.e setup the environment correctly before the test)

You can notice the difference in my RoomCreationHandler, I'haven't call SetupTest since testify will automatically handle that. 

Your setup is not setting up the environment before the tests so it will not work. Try to follow the example I've linked so that your workflow looks like the following:

- [ ] All your tests should be part of the suite just like RoomCreationHandler in my example
- [ ] The tests should be bootstrapped from one function just like what I've done for TestGraphQLTestSuite

This should be a fairly simple and minor refactor. In fact, you can just make your changes over my unit-test branch and then make the pull request.

2021-02-03 18:00 UTC, raysandeep commented
Got it. I'll update in few mins.

2021-02-03 18:25 UTC, samyak-jain requested changes

2021-02-03 18:25 UTC, samyak-jain commented on server_test.go
>  	GraphQLTestSuite.SetupSuite()
You should be using the suite object passed as a parameter rather than creating a new GraphQLTestSuite

2021-02-03 19:09 UTC, raysandeep commented on server_test.go
>  	GraphQLTestSuite.SetupSuite()
Oh yeah shit. I'll change it

2021-02-19 07:27 UTC, raysandeep commented
@samyak-jain I've added Database Testing as well. For the Join room handler there is no need for DB Testing coz we are not appending anything to DB.

2021-03-04 13:06 UTC, samyak-jain requested changes

2021-03-04 13:06 UTC, samyak-jain commented on server_test.go
> +	return decodedResponse
1. Try putting more data. Use Table Driven Development along with faker libraries to generate relevant and deterministic data. 
2. You are checking assertions for few of the variables. Check for all of them. For example, when enablePSTN is not true, the backend should not be generating any PSTN credentials. You need to test for that.

2021-03-04 13:06 UTC, samyak-jain commented on server_test.go
> +func (suite *GraphQLTestSuite) RoomCreation(t *testing.T) {
There's no need to add t as a parameter for functions that are part of the test suite.

2021-03-05 13:04 UTC, raysandeep commented on server_test.go
> +func (suite *GraphQLTestSuite) RoomCreation(t *testing.T) {
Okay. I'll remove it. Probably used it to debug

2021-03-05 13:05 UTC, raysandeep commented on server_test.go
> +	return decodedResponse
Okay got it

2021-03-23 15:15 UTC, samyak-jain commented on server_test.go
> +	return decodedResponse
Did you get a chance to look into this?

2021-03-25 15:34 UTC, merged